//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Management_Slammer.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Prisoner
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public Nullable<int> Age { get; set; }
        public string Sex { get; set; }
        public Nullable<int> Phone { get; set; }
        public Nullable<int> Erea { get; set; }
        public Nullable<int> Accusation { get; set; }
        public Nullable<System.DateTime> Date_Of_Enter { get; set; }
        public string Judgement { get; set; }
        public Nullable<int> Punshment { get; set; }
        public Nullable<System.DateTime> Date_Of_Out { get; set; }
    
        public virtual Accusation Accusation1 { get; set; }
        public virtual Erea Erea1 { get; set; }
        public virtual Punishment Punishment { get; set; }
    }
}
